portfolio_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('weather/', include('weather.urls')),
    path('polls/', include('polls.urls')),
    path('login_system/', include('login_system.urls')),
    path('schoolms/', include('schoolms.urls')),
]

schoolms/urls.py
from django.urls import path
from . import views

app_name = 'schoolms'
urlpatterns = [
    path('', views.index, name='index'),
    path('get_start/', views.get_start, name='get_start'),
    path('create_account/', views.create_account, name='create_account'),
    path('login_page/', views.login_page, name='login_page'),
    path('log_in/', views.log_in, name='log_in'),
    path('create_new_group/<int:professor_id>/', views.create_new_group, name='create_new_group'),
    path('add_new_student/<int:group_id>/', views.add_new_student, name='add_new_student'),
    path('student_dashboard/<int:group_dash_id>/', views.student_dashboard, name='student_dashboard'),
    path('delete_student/<int:student_del_id>/', views.delete_student, name='delete_student'),
    path('delete_group/<int:group_del_id>/', views.delete_group, name='delete_group'),
    path('edit_group_information/<int:edit_group_id>/', views.edit_group_information, name='edit_group_information'),
]

todo/urls.py
from django.urls import path
from . import views

app_name = "todo"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.CategoryDetailView.as_view(), name='detail'),
    path('create_category/', views.create_category, name='create_category'),
    path('create_task/', views.create_task, name='create_task'),
    path('task_delete/', views.task_delete, name='task_delete'),
]

schoolms/models.py
from django.db import models

# Create your models here.
class Professor(models.Model):
    user_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    password = models.CharField(max_length=50)

    def __str__(self):
        return self.user_name

class Group(models.Model):
    professor = models.ForeignKey(Professor, on_delete=models.CASCADE)
    group_name = models.CharField(max_length=50)
    academic_level = models.CharField(max_length=50)

    def __str__(self):
        return self.group_name

class Student(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    age = models.IntegerField(blank=True)
    genre = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Subject(models.Model):
    student = models.ManyToManyField(Student, through="Subjectmarks")
    subject_name = models.CharField(max_length=50)

    def __str__(self):
        return self.subject_name

class Subjectmarks(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    first_tcp_mark = models.IntegerField(blank=True)
    second_tcp_mark = models.IntegerField(blank=True)
    third_tcp_mark = models.IntegerField(blank=True)
    final_test_mark = models.IntegerField(blank=True)
    extra_test_mark = models.IntegerField(blank=True)
    mundial_test_mark = models.IntegerField(blank=True)

schoolms/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Professor, Group, Student, Subject

# Create your views here.
def index(request):
    return render(request, "schoolms/index.html")

def get_start(request):
    return render(request, "schoolms/get_start.html")

def create_account(request):
    username = request.POST['username_prof']
    email = request.POST['email_prof']
    password = request.POST['password_prof']
    if Professor.objects.filter(user_name=username).exists():
        error_message = "Username has already been taken. Please enter a different one."
        context = {
            "error_message": error_message
        }
        return render(request, "schoolms/get_start.html", context)
    else:
        new_account = Professor(user_name=username, email=email, password=password)
        new_account.save()
        success_created = "Account succesfully created, please log in to continue."
        context = {
            "success_created": success_created,
        }
        return render(request, "schoolms/login_page.html", context)

def login_page(request):
    return render(request, "schoolms/login_page.html")

def log_in(request):
    user = request.POST['user_login']
    password = request.POST['password_login']
    if Professor.objects.filter(user_name=user, password=password).exists():
        professor = Professor.objects.get(user_name=user, password=password)
        professor_groups = professor.group_set.all()
        context = {
            "professor": professor,
            "professor_groups": professor_groups
        }
        return render(request, "schoolms/account.html", context)
    else:
        error_login_msg = "Incorrect username or password. Please try again."
        context = {
            "error_login_msg": error_login_msg
        }
        return render(request, "schoolms/login_page.html", context)

def create_new_group(request, professor_id):
    professor = Professor.objects.get(id=professor_id)
    group_name = request.POST['group_name']
    academic_level = request.POST['academic_level']
    professor.group_set.create(group_name=group_name, academic_level=academic_level)
    professor_groups = professor.group_set.all()
    context = {
        "professor": professor,
        "professor_groups": professor_groups
    }
    return render(request, "schoolms/account.html", context)

def add_new_student(request, group_id):
    student_name = request.POST['student_name']
    student_age = int(request.POST['student_age'])
    student_genre = request.POST['student_genre']
    group = Group.objects.get(id=group_id)
    group.student_set.create(name=student_name, age=student_age, genre=student_genre)
    professor = Professor.objects.get(id=group.professor_id)
    professor_groups = professor.group_set.all()
    context = {
        "professor": professor,
        "professor_groups": professor_groups
    }
    return render(request, "schoolms/account.html", context)

def student_dashboard(request, group_dash_id):
    group = Group.objects.get(id=group_dash_id)
    students = group.student_set.all()
    professor = Professor.objects.get(id=group.professor_id)
    context = {
        "group": group,
        "students": students,
        "professor": professor
    }
    return render(request, "schoolms/student_dashboard.html", context)

def delete_student(request, student_del_id):
    del_student = Student.objects.get(id=student_del_id)
    group = Group.objects.get(id=del_student.group_id)
    del_student.delete()
    # students = group.student_set.all()
    # professor = Professor.objects.get(id=group.professor_id)
    return HttpResponseRedirect(reverse('schoolms:student_dashboard', args=(group.id,)))

def delete_group(request, group_del_id):
    group = Group.objects.get(id=group_del_id)
    professor = Professor.objects.get(id=group.professor_id)
    group.delete()
    professor_groups = professor.group_set.all()
    context = {
        "professor": professor,
        "professor_groups": professor_groups
    }
    return render(request, "schoolms/account.html", context)

def edit_group_information(request, edit_group_id):
    edit_group_name = request.POST['edit_group_name']
    edit_academic_level = request.POST['edit_academic_level']
    edit_group = Group.objects.get(id=edit_group_id)
    edit_group.group_name = edit_group_name
    edit_group.academic_level = edit_academic_level
    edit_group.save()
    professor = Professor.objects.get(id=edit_group.professor_id)
    professor_groups = professor.group_set.all()
    context = {
        "professor": professor,
        "professor_groups": professor_groups
    }
    return render(request, "schoolms/account.html", context)

schoolms/templates/schoolms/add_group.html
<!-- Modal toggle -->
<button data-modal-target="add-group-modal-{{professor.id}}" data-modal-toggle="add-group-modal-{{professor.id}}" class="block text-white bg-gray-700 hover:bg-gray-800 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm text-center dark:bg-gray-800 dark:hover:bg-gray-800 dark:focus:ring-gray-800 flex items-center border-dashed border-2 border-white px-3" type="button">
    Add Group <span class="prose-2xl ml-1">+</span>
</button>
  
  <!-- Main modal -->
<div id="add-group-modal-{{professor.id}}" tabindex="-1" aria-hidden="true" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative w-full max-w-md max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <button type="button" class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ml-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="add-group-modal-{{professor.id}}">
                <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                </svg>
                <span class="sr-only">Close modal</span>
            </button>
            <div class="px-6 py-6 lg:px-8">
                <h3 class="mb-4 text-xl font-medium text-gray-900 dark:text-white">Add a new student group</h3>
                <form class="space-y-6" action="{% url 'schoolms:create_new_group' professor.id %}" method="post">
                    {% csrf_token %}
                    <div>
                        <label for="group_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Enter Group Name</label>
                        <input type="text" name="group_name" id="group_name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="group name" required>
                    </div>
                    <div>
                        <label for="academic_level" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Select Academic Level</label>
                        <select id="academic_level" name="academic_level" autocomplete="category-name" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6">
                            <option>Unversity First Year</option>
                            <option>Unversity Second Year</option>
                            <option>Unversity Third Year</option>
                            <option>Unversity Fourth Year</option>
                            <option>Unversity Fifth Year</option>
                            <option>Baccalaureate First Year</option>
                            <option>Baccalaureate Second Year</option>
                            <option>Baccalaureate Third Year</option>
                            <option>ESO First Year</option>
                            <option>ESO Second Year</option>
                            <option>ESO Third Year</option>
                        </select>
                    </div>
                    <button type="submit" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Create</button>
                </form>
            </div>
        </div>
    </div>
</div>

schoolms/templates/schoolms/add_student_modal.html
<div id="add-student-modal-{{group.id}}" tabindex="-1" aria-hidden="true" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative w-full max-w-md max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <button type="button" class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ml-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-hide="add-student-modal-{{group.id}}">
                <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                </svg>
                <span class="sr-only">Close modal</span>
            </button>
            <div class="px-6 py-6 lg:px-8">
                <h3 class="mb-4 text-xl font-medium text-gray-900 dark:text-white">Add a new student to the group</h3>
                <form class="space-y-6" action="{% url 'schoolms:add_new_student' group.id %}" method="post">
                    {% csrf_token %}
                    <div>
                        <label for="student_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Enter Student's Full Name</label>
                        <input type="text" name="student_name" id="student_name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="student's full name" required>
                    </div>
                    <div>
                        <label for="student_age" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Enter Student Age</label>
                        <input type="text" name="student_age" id="student_age" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" placeholder="student age" required>
                    </div>
                    <div>
                        <label for="student_genre" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Select Student Genre</label>
                        <select id="student_genre" name="student_genre" autocomplete="category-name" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6">
                            <option>Female</option>
                            <option>Male</option>
                        </select>
                    </div>
                    <button type="submit" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>

schoolms/templates/schoolms/delete_group_btn.html
<a href="{% url 'schoolms:delete_group' group.id %}" class="inline-flex items-center px-2 py-2 bg-red-600 hover:bg-red-700 text-white text-sm font-medium rounded-full" data-tooltip-target="tooltip-delete-group">
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
    <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
  </svg>  
</a>
<div id="tooltip-delete-group" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:bg-gray-700">
    Delete Group
    <div class="tooltip-arrow" data-popper-arrow></div>
</div>

schoolms/templates/schoolms/get_start.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
        <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css" rel="stylesheet" />
        <title>Document</title>
    </head>
    <body>
        {% include 'schoolms/header.html' %}

        <!-- show vanishing alert -->
        {% if error_message %}
            <div class="flex items-center bg-red-500 text-white text-sm font-bold px-4 py-3" role="alert">
                <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
                <p>{{error_message}}</p>
            </div>
        {% endif %}

        <!-- show the create account form -->
        <section class="bg-gray-50 dark:bg-gray-900">
            <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto h-screen lg:py-0">
                <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
                    <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                            Create your account
                        </h1>
                        <form class="space-y-4 md:space-y-6" action="{% url 'schoolms:create_account' %}" method="post">
                            {% csrf_token %}
                            <div>
                                <label for="username_prof" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Enter Username</label>
                                <input type="text" name="username_prof" id="username_prof" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="username" required>
                            </div>
                            <div>
                                <label for="email_prof" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Enter Email</label>
                                <input type="email_prof" name="email_prof" id="email_prof" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="name@company.com" required>
                            </div>
                            <div>
                                <label for="password_prof" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Enter Password</label>
                                <input type="password" name="password_prof" id="password_prof" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required>
                            </div>
                            <button type="submit" class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Create Account</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></script>
    </body>
</html>

schoolms/templates/schoolms/login_page.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
        <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css" rel="stylesheet" />
        <title>Document</title>
    </head>
    <body>
        {% include 'schoolms/header.html' %}

        <!-- show vanishing alert -->
        {% if success_created %}
            <div class="flex items-center bg-green-500 text-white text-sm font-bold px-4 py-3" role="alert">
                <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
                <p>{{success_created}}</p>
            </div>
        {% endif %}

        {% if error_login_msg %}
            <div class="flex items-center bg-red-500 text-white text-sm font-bold px-4 py-3" role="alert">
                <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
                <p>{{error_login_msg}}</p>
            </div>
        {% endif %}

        <!-- show the create account form -->
        <section class="bg-gray-50 dark:bg-gray-900">
            <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto h-screen lg:py-0">
                <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
                    <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                            Sign in to your account
                        </h1>
                        <form class="space-y-4 md:space-y-6" action="{% url 'schoolms:log_in' %}" method="post">
                            {% csrf_token %}
                            <div>
                                <label for="user_login" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Enter Username</label>
                                <input type="text" name="user_login" id="user_login" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="username or email" required>
                            </div>
                            <div>
                                <label for="password_login" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Enter Password</label>
                                <input type="password" name="password_login" id="password_login" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required>
                            </div>
                            <button type="submit" class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Log in</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></script>
    </body>
</html>

schoolms/templates/schoolms/student_dashboard.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
        <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css" rel="stylesheet" />
        <title>Document</title>
    </head>
    <body>
        {% if group %}
            {% if students %}
                {% include 'schoolms/student_table.html' %}
            {% else %}
                {% include 'schoolms/empty_student.html' %}
            {% endif %}
            <form action="{% url 'schoolms:log_in' %}" method="post" class="flex justify-center">
                {% csrf_token %}
                {% if professor %}
                    <input type="text" name="user_login" value="{{professor.user_name}}" hidden>
                    <input type="text" name="password_login" value="{{professor.password}}" hidden>
                {% endif %}
                <button type="submit" class="text-white bg-[#3b5998] hover:bg-[#3b5998]/90 focus:ring-4 focus:outline-none focus:ring-[#3b5998]/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:focus:ring-[#3b5998]/55 mr-2 mb-2">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M9 15L3 9m0 0l6-6M3 9h12a6 6 0 010 12h-3" />
                    </svg>                  
                    Go Back
                </button>
            </form>
        {% endif %}

        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></script>
    </body>
</html>