login_system/urls.py
from django.urls import path
from . import views

app_name = "login_system"
urlpatterns = [
    path('', views.index, name='index'),
    path('log_in/', views.log_in, name='log_in'),
    path('create_account/', views.create_account, name='create_account'),
    path('create_new_account/', views.create_new_account, name='create_new_account'),
]

portfolio_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('weather/', include('weather.urls')),
    path('polls/', include('polls.urls')),
    path('login_system/', include('login_system.urls')),
    path('schoolms/', include('schoolms.urls')),
]

todo/urls.py
from django.urls import path
from . import views

app_name = "todo"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.CategoryDetailView.as_view(), name='detail'),
    path('create_category/', views.create_category, name='create_category'),
    path('create_task/', views.create_task, name='create_task'),
    path('task_delete/', views.task_delete, name='task_delete'),
]

login_system/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    user_name = models.CharField(max_length=50)
    password = models.CharField(max_length=10)
    secret_phrase = models.CharField(max_length=100)

    def __str__(self):
        return self.user_name

login_system/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import User

# Create your views here.
def index(request):
    return render(request, "login_system/index.html")

def log_in(request):
    username = request.POST['username']
    password = request.POST['password']
    secret_phrase = request.POST['secret']
    if User.objects.filter(user_name=username, password=password, secret_phrase=secret_phrase).exists():
        user_account = User.objects.get(user_name=username, password=password, secret_phrase=secret_phrase)
        context = {
            "user": user_account
        }
        return render(request, "login_system/account.html", context)
    else:
        context = {
            "error_message": "User Name, Password or Secret Phrase incorrect."
        }
        return render(request, "login_system/index.html", context)

def create_account(request):
    return render(request, "login_system/create_account.html")

def create_new_account(request):
    new_username = request.POST['created_username']
    new_password = request.POST['created_password']
    new_secret_phrase = request.POST['created_secret']
    if User.objects.filter(user_name=new_username).exists():
        error_message = "User Name it's already been taken. Please tap a different one."
        context = {
            "error_message": error_message
        }
        return render(request, "login_system/create_account.html", context)
    else:
        new_account = User(user_name=new_username, password=new_password, secret_phrase=new_secret_phrase)
        new_account.save()
        return HttpResponseRedirect(reverse("login_system:index"))

login_system/templates/login_system/account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css" rel="stylesheet" />
    <title>Document</title>
</head>
<body>
    {% if user %}
        {% include 'login_system/header.html' %}
        <h1 class="prose-xl m-5">wellcome {{user.user_name}}!</h1>
        <p class="m-5">
            We hope you join us in this adventure and enjoy!
        </p>
    {% endif %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></script>
</body>
</html>

login_system/templates/login_system/create_account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css" rel="stylesheet" />
    <title>Document</title>
</head>
<body class="h-screen">

    <div class="bg-[url(https://wallpapercave.com/wp/ejtksZp.jpg)] bg-no-repeat bg-cover bg-auto h-full">
        <h1 class="flex justify-center prose-2xl p-5 font-bold text-white">Login System App</h1>

        <section class="bg-inherit">
            <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
                <div class="w-full bg-inherit rounded-lg shadow md:mt-0 sm:max-w-md xl:p-0">
                    <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                            Tap your credentials
                        </h1>
                        <form class="space-y-4 md:space-y-6" action="{% url 'login_system:create_new_account' %}" method="post">
                            {% csrf_token %}
                            <div class="bg-inherit">
                                <input type="text" name="created_username" id="username" class="bg-inherit text-white sm:text-sm block w-full p-2.5 dark:placeholder-white dark:text-white border-transparent ring-0" placeholder="Tap User Name" required="" />
                            </div>
                            <div class="bg-inherit">
                                <input type="password" name="created_password" id="password" placeholder="Tap Password" class="bg-inherit text-white sm:text-sm block w-full p-2.5 dark:placeholder-white dark:text-white border-transparent ring-0" required />
                            </div>
                            <div class="bg-inherit">
                                <input type="password" name="created_secret" id="secret" placeholder="Tap Secret Phrase" class="bg-inherit text-white sm:text-sm block w-full p-2.5 dark:placeholder-white dark:text-white border-transparent ring-0" required />
                            </div>
                            <button type="submit" class="w-auto bg-inherit text-white bg-primary-600 hover:bg-primary-700 focus:outline-none font-medium rounded-lg text-sm px-5 py-2.5 text-center">Create Account</button>
                            <a href="{% url 'login_system:index' %}" class="w-auto bg-inherit text-white bg-primary-600 hover:bg-primary-700 focus:outline-none font-medium rounded-lg text-sm px-5 py-2.5 text-center">Log in page</a>
                            
                            {% if error_message %}
                                <div class="flex items-center bg-red-500 text-white text-sm font-bold px-4 py-3" role="alert">
                                    <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
                                    <p>{{error_message}}</p>
                                </div>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></script>
</body>
</html>

login_system/templates/login_system/header.html
<header>
    <nav class="bg-white border-gray-200 px-4 lg:px-6 py-2.5 dark:bg-gray-800">
        <div class="flex flex-wrap justify-end items-end mx-auto max-w-screen-xl">
            <button id="dropdownHoverButton" data-dropdown-toggle="dropdownHover" data-dropdown-trigger="hover" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="button">account<svg class="w-2.5 h-2.5 ml-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
            </svg></button>
            <!-- Dropdown menu -->
            <div id="dropdownHover" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
                <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownHoverButton">
                    <li>
                        <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Dashboard</a>
                    </li>
                    <li>
                        <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Settings</a>
                    </li>
                    <li>
                        <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Earnings</a>
                    </li>
                    <li>
                        <a href="{% url 'login_system:index' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white">Log out</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

login_system/templates/login_system/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css" rel="stylesheet" />
    <title>Document</title>
</head>
<body class="h-screen">

    <div class="bg-[url(https://wallpapercave.com/wp/ejtksZp.jpg)] bg-no-repeat bg-cover bg-auto h-full">
        <h1 class="flex justify-center prose-2xl p-5 font-bold text-white">Login System App</h1>

        <section class="bg-inherit">
            <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
                <div class="w-full bg-inherit rounded-lg shadow md:mt-0 sm:max-w-md xl:p-0">
                    <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                            Log in to your account
                        </h1>
                        <form class="space-y-4 md:space-y-6" action="{% url 'login_system:log_in' %}" method="post">
                            {% csrf_token %}
                            <div class="bg-inherit">
                                <input type="text" name="username" id="username" class="bg-inherit text-white sm:text-sm block w-full p-2.5 dark:placeholder-white dark:text-white border-transparent ring-0" placeholder="Tap User Name" required="" />
                            </div>
                            <div class="bg-inherit">
                                <input type="password" name="password" id="password" placeholder="Tap Password" class="bg-inherit text-white sm:text-sm block w-full p-2.5 dark:placeholder-white dark:text-white border-transparent ring-0" required />
                            </div>
                            <div class="bg-inherit">
                                <input type="password" name="secret" id="secret" placeholder="Tap Secret Phrase" class="bg-inherit text-white sm:text-sm block w-full p-2.5 dark:placeholder-white dark:text-white border-transparent ring-0" required />
                            </div>
                            <button type="submit" class="w-auto bg-inherit text-white bg-primary-600 hover:bg-primary-700 focus:outline-none font-medium rounded-lg text-sm px-5 py-2.5 text-center">Log in</button>
                            <div class="flex items-center justify-between">
                                <a href="#" class="text-sm font-medium text-primary-600 hover:underline dark:text-primary-500">Forgot password?</a>
                            </div>
                            <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                                Do not have an account yet? <a href="#" class="font-medium text-primary-600 hover:underline dark:text-primary-500">Create account</a>
                            </p>
                            {% if error_message %}
                                <div class="flex items-center bg-red-500 text-white text-sm font-bold px-4 py-3" role="alert">
                                    <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
                                    <p>{{error_message}}</p>
                                </div>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></script>
</body>
</html>