portfolio_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('weather/', include('weather.urls')),
    path('polls/', include('polls.urls')),
    path('login_system/', include('login_system.urls')),
    path('schoolms/', include('schoolms.urls')),
]

todo/urls.py
from django.urls import path
from . import views

app_name = "todo"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.CategoryDetailView.as_view(), name='detail'),
    path('create_category/', views.create_category, name='create_category'),
    path('create_task/', views.create_task, name='create_task'),
    path('task_delete/', views.task_delete, name='task_delete'),
]

todo/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=50)
    pub_date = models.DateTimeField("date created")

class Task(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    task_description = models.CharField(max_length=200)
    created_at = models.DateTimeField("date started")

todo/views.py
from typing import Any
from django.db import models
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils import timezone
from .models import Category, Task
from .labels import categories_label

# Create your views here.
class IndexView(generic.ListView):
    template_name = "todo/index.html"
    context_object_name = "categories_and_labels"

    def get_queryset(self):
        categories = Category.objects.all()
        for label in categories_label:
            for category in categories:
                if label["category"] == category.category_name:
                    label["stored"] = True
        context = {
            "categories": categories,
            "categories_label": categories_label
        }
        return context

class CategoryDetailView(generic.DetailView):
    model = Category
    template_name = "todo/category_detail.html"

    def get_queryset(self):
        return Category.objects.all()

def create_category(request):
    new_category_name = request.POST['category']
    new_category = Category(category_name=new_category_name, pub_date=timezone.now())
    new_category.save()
    return HttpResponseRedirect(reverse('todo:index'))

def create_task(request):
    category = Category.objects.get(pk=request.POST['category_id'])
    category.task_set.create(
        task_description=request.POST['task_description'],
        created_at=timezone.now()
    )
    return HttpResponseRedirect(reverse('todo:detail', args=(request.POST['category_id'],)))

def task_delete(request):
    category = Category.objects.get(pk=request.POST['category_id_del'])
    task = category.task_set.filter(pk=request.POST['task_id_del'])
    task.delete()
    return HttpResponseRedirect(reverse('todo:detail', args=(request.POST['category_id_del'],)))

todo/templates/todo/category_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css" rel="stylesheet" />
    <title>Document</title>
</head>
<body>
    {% include "todo/header.html" %}
    
    {% if category.task_set.all %}
        <ul role="list" class="divide-y divide-gray-100 mt-7 justify-center m-2 overflow-y-auto h-80">
            {% for task in category.task_set.all %}
                <li class="flex justify-between gap-x-6 py-5">
                    <div class="flex gap-x-4">
                        <article class="min-w-0 flex-auto">
                            <time class="mt-1 text-xs leading-5 text-gray-500">{{ task.created_at }}</time>
                            <h2 class="font-semibold leading-6 text-gray-900">{{task.task_description}}</h2>
                        </article>
                    </div>
                    <form action="{% url 'todo:task_delete' %}" method="post">
                        {% csrf_token %}
                        <input type="text" id="category_id_del" name="category_id_del" value="{{category.id}}" hidden>
                        <input type="text" id="task_id_del" name="task_id_del" value="{{task.id}}" hidden>
                        <button href="#" type="submit" class="mr-2 text-white bg-red-600 hover:bg-red-700 focus:ring-0 focus:outline-none focus:ring-red-300 font-medium rounded-full text-sm p-3.5 text-center inline-flex items-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                            </svg>
                            <span class="sr-only">Icon description</span>
                        </button>
                    </form>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <div class="my-6 flex justify-center grid grid-flow-row auto-rows-max">
            <strong>No Task.</strong>
            <span>Please add one to store.</span>
        </div>
    {% endif %}

    <form action="{% url 'todo:create_task' %}" method="post" class="m-2">
        {% csrf_token %}
        <div class="container mx-auto p-4 justify-center border-none">
            <div class="sm:col-span-3 mr-1">
                <label for="task_description" class="text-sm font-medium leading-6 text-gray-900">Enter Task Description</label>
                <div class="mt-2">
                    <input id="task_description" name="task_description" placeholder="Tap description here..." class="block w-full rounded-md border-none py-1.5 text-gray-900 placeholder:text-gray-400 sm:text-sm sm:leading-6 focus:ring-0" required></input>
                    <input type="text" id="category_id" name="category_id" value="{{ category.id }}" hidden>
                </div>
            </div>
            <div class="flex p-1 items-center justify-center">
              <button data-tooltip-target="tooltip-default" type="submit" class="rounded-full bg-teal-900 px-3 py-2 text-sm font-semibold text-white shadow-lg shadow-indigo-500/50 hover:bg-teal-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" style="font-size: 1.2rem;">+</button>
              <div id="tooltip-default" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:bg-gray-700">
                Save Task
                <div class="tooltip-arrow" data-popper-arrow></div>
            </div>
            </div>
        </div>
    </form>

    <div class="flex mt-1 p-4 justify-center border-none">
        <a href="{% url 'todo:index' %}" class="rounded-lg bg-teal-900 px-3 py-2 text-sm font-semibold text-white shadow-lg shadow-indigo-500/50 hover:bg-teal-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Back to Categories</a>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></script>
</body>
</html>

todo/templates/todo/header.html
<header class="flex bg-teal-900 justify-center pb-8 items-start shadow-md shadow-teal-900/40" style="border-radius: 0px 0px 30% 30%;">
    <h1 class="text-zinc-100 text-2xl py-4 m-0">Todo Tasks App</h1>
</header>

todo/templates/todo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    <title>Document</title>
</head>
<body>
    {% include "todo/header.html" %}

    {% if categories_and_labels.categories %}
        <div class="flex md:container md:mx-auto grid grid-cols-3 gap-2 m-2 mt-10 mb-10">
            {% for category in categories_and_labels.categories %}
                {% if category.task_set.all.count > 0 %}
                    <a href="{% url 'todo:detail' category.id %}" class="border-2 text-center p-3 rounded-lg text-teal-300 shadow hover:shadow-lg transition ease-in-out delay-0 hover:-translate-y-1 hover:scale-105 duration-700 bg-teal-900">
                        {{category.category_name}}
                    </a>
                {% else %}
                    <a href="{% url 'todo:detail' category.id %}" class="border-2 text-center p-3 rounded-lg text-teal-700 shadow hover:shadow-lg transition ease-in-out delay-0 hover:-translate-y-1 hover:scale-105 duration-700">
                        {{category.category_name}}
                    </a>
                {% endif %}
            {% endfor %}
        </div>
    {% else %}
        <div class="my-6 flex justify-center grid grid-flow-row auto-rows-max">
            <strong>No Category found.</strong>
            <span>Please add one to start.</span>
        </div>
    {% endif %}

    <form action="{% url 'todo:create_category' %}" method="post">
        {% csrf_token %}
        <div class="flex justify-center">
            <div class="sm:col-span-3 mr-1">
                <label for="category" class="text-sm font-medium leading-6 text-gray-900">Select Category</label>
                <div class="mt-2">
                    <select id="category" name="category" autocomplete="category-name" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6">
                        {% for label in categories_and_labels.categories_label %}
                            {% if label.stored %}
                                <option disabled>{{label.category}}</option>
                            {% else %}
                                <option>{{label.category}}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="mt-8 items-center justify-center gap-x-6">
              <button type="submit" class="rounded-md bg-teal-900 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-teal-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Add</button>
            </div>
        </div>
    </form>
</body>
</html>